update_data_job:
  cron: "*/15 * * 9 *"
  class: "UpdateDataWorker"
update_global_usage_job:
  cron: "01 0 * 9 *"
  class: "UpdateDataWorker"
update_photos_count_job:
  cron: "*/5 * * 9 *"
  class: "UpdatePhotosCountWorker"
first_wlm_data_population_worker:
  cron: "30 7 31 8 *"
  class: "FirstWlmDataPopulationWorker"
update_nophoto_data_worker:
  cron: "30 7 * 9 *"
  class: "UpdateNophotoDataWorker"