---
update_data_job:
  cron: "<%= "*/5 * * #{ENV["MONTHS"]} *" %>"
  class: "UpdateDataWorker"
update_global_usage_job:
  cron: "<%= "*/30 * * #{ENV["MONTHS"]} *" %>"
  class: "UpdateGlobalUsageWorker"
update_photos_count_job:
  cron: "<%= "*/5 * * #{ENV["MONTHS"]} *" %>"
  class: "UpdatePhotosCountWorker"
first_wlm_data_population_worker:
  cron: "<%= "30 7 31 #{ENV["MONTH_BEFORE"]} *" %>"
  class: "FirstWlmDataPopulationWorker"
update_nophoto_data_worker:
  cron: "<%= "0 10 * #{ENV["MONTH"]} *" %>"
  class: "UpdateNophotoDataWorker"
delete_nonwlm_photos_worker:
  cron: "<%= "00 23 * #{ENV["MONTHS"]} *" %>"
  class: "DeleteNonwlmPhotosWorker"
download_no_photo_monuments:
  cron: "<%= "0 0 31 #{ENV["MONTH_BEFORE"]} *" %>"
  class: "DownloadNoPhotoMonuments"